# Generated by Django 2.2.5 on 2019-09-18 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('koroibos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sport',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='koroibos.Sport'),
            preserve_default=False,
        ),
    ]
